server:
  port: 8081

spring:
  h2:
    console:
      enabled: true

  #h2
  #datasource:
  #  url: jdbc:h2:mem:testdb

  #postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/edudb
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/rootChangeLog.xml

  jpa:
    generate-ddl: false
    #generate-ddl: true
    hibernate:
      ddl-auto: none
      #ddl-auto: create-drop
    show-sql: true
