package ru.diasoft.edu.dto.converter;

import lombok.experimental.UtilityClass;
import ru.diasoft.edu.domain.Person;
import ru.diasoft.edu.dto.PersonDto;

import java.util.stream.Collectors;

@UtilityClass
// will be made final
public class PersonConverter {

    // autogenerated by Lombok
    // private PersonConverter() {
    //   throw new java.lang.UnsupportedOperationException("This is a utility class and cannot be instantiated");
    //}

    // will be made static
    public PersonDto toDto(Person person) {

        PersonDto personDto = PersonDto.builder()
                .id(person.getId())
                .name(person.getName())
                .build();

        if (person.getEmails() != null) {
            personDto.setEmails(
                    person.getEmails().stream()
                            .map(EmailConverter::toDto)
                            .collect(Collectors.toSet())
            );
        }
        return personDto;
    }

    // will be made static
    public Person toEntity(PersonDto personDto) {

        Person person = new Person();
        person.setId(personDto.getId());
        person.setName(personDto.getName());
        if (personDto.getEmails() != null) {
            person.setEmails(personDto.getEmails().stream()
                    .map(email -> EmailConverter.toEntity(email, person))
                    .collect(Collectors.toSet()));
        }
        return person;
    }
}
